AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation template to create AWS Config Managed Rules with resource type configuration.
 
Resources:
  LambdaFunctionPublicAccessProhibited:
    Type: "AWS::Config::ConfigRule"
    Properties:
      ConfigRuleName: "ffs-lambda-function-public-access-prohibited"
      Source:
        Owner: "AWS"
        SourceIdentifier: "LAMBDA_FUNCTION_PUBLIC_ACCESS_PROHIBITED"
      Scope:
        ComplianceResourceTypes:
          - "AWS::Lambda::Function"
 
  LambdaInsideVPC:
    Type: "AWS::Config::ConfigRule"
    Properties:
      ConfigRuleName: "ffs-lambda-inside-vpc"
      Source:
        Owner: "AWS"
        SourceIdentifier: "LAMBDA_INSIDE_VPC"
      Scope:
        ComplianceResourceTypes:
          - "AWS::Lambda::Function"
 
  S3BucketLevelPublicAccessProhibited:
    Type: "AWS::Config::ConfigRule"
    Properties:
      ConfigRuleName: "ffs-s3-bucket-level-public-access-prohibited"
      Source:
        Owner: "AWS"
        SourceIdentifier: "S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED"
      Scope:
        ComplianceResourceTypes:
          - "AWS::S3::Bucket"
 
  S3BucketLoggingEnabled:
    Type: "AWS::Config::ConfigRule"
    Properties:
      ConfigRuleName: "ffs-s3-bucket-logging-enabled"
      Source:
        Owner: "AWS"
        SourceIdentifier: "S3_BUCKET_LOGGING_ENABLED"
      Scope:
        ComplianceResourceTypes:
          - "AWS::S3::Bucket"
